/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-10-18 05:39:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.reply;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Start Simple Web</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"/Web/boardMVC/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<!-- <link href=\"css/login.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("<link href=\"/Web/boardMVC/css/clean-blog.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("	href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'\r\n");
      out.write("	rel='stylesheet' type='text/css'>\r\n");
      out.write("<link\r\n");
      out.write("	href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'\r\n");
      out.write("	rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(function(){\r\n");
      out.write("    	$(\"a#signin\").click(function(){\r\n");
      out.write("    		if($(\"input#id\").val().length==0||($(\"input#password\").val().length)==0){\r\n");
      out.write("    			alert(\"ID or PASS check\");\r\n");
      out.write("    			$(\"input#id\").val('');\r\n");
      out.write("    			$(\"input#password\").val('');\r\n");
      out.write("    			return false;\r\n");
      out.write("    		}\r\n");
      out.write("    		$.ajax({\r\n");
      out.write("    			url:'/Web/ajaxLogin.do',\r\n");
      out.write("    			type:'POST',\r\n");
      out.write("    			dataType:'text',\r\n");
      out.write("    			data:{id:'$(\"input#id\").val()',pw:'$(\"input#id\").val()'},\r\n");
      out.write("    			success:function(v){\r\n");
      out.write("    				console.log(v);\r\n");
      out.write("    			},\r\n");
      out.write("    			error:function(e){\r\n");
      out.write("    				alert('error'+e);\r\n");
      out.write("    			}\r\n");
      out.write("    			\r\n");
      out.write("    		});\r\n");
      out.write("    	});\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-image: url(/Web/boardMVC/img/back.jpg)\">\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/boardMVC/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"container\" style=\"margin-top: 120px\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"main\">\r\n");
      out.write("				<h3>\r\n");
      out.write("					SAMPLE SIGN IN</a>\r\n");
      out.write("				</h3>\r\n");
      out.write("\r\n");
      out.write("				<form name=\"LoginFrm\" method=\"post\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<input type=\"text\" placeholder=\"ID \" class=\"form-control\"\r\n");
      out.write("							id=\"id\" name=\"id\"/>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<!--<a class=\"pull-right\" href=\"#\">Esqueci a senha</a>-->\r\n");
      out.write("						<input type=\"password\" placeholder=\"PASSWORD \" class=\"form-control\"\r\n");
      out.write("							id=\"password\" name=\"password\"/>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-xs-12 col-sm-12 col-md-12\">\r\n");
      out.write("							<a href=\"#\" id=\"signin\" class=\"btn btn-sm btn-danger btn-block\">SIGN IN</a>\r\n");
      out.write("						</div>0\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"login-or\">\r\n");
      out.write("						<hr class=\"hr-or\">\r\n");
      out.write("						<span class=\"span-or\">or</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-xs-12 col-sm-12 col-md-12\">\r\n");
      out.write("							<a href=\"signup.jsp\" class=\"btn btn-sm btn-info btn-block\">SIGN UP</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h6 style=\"font-weight: 400;font-size: 0.85714rem; color: gray \" align=\"center\">\r\n");
      out.write("						비밀번호가 기억나지 않으세요? <u><a href=\"#\">비밀번호재설정</a></u>\r\n");
      out.write("					</h6>\r\n");
      out.write("				</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
