/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-10-17 07:48:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.boardMVC;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC >\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Start Simple Web</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"css/clean-blog.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/board.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("   href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\"\r\n");
      out.write("   rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("   href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'\r\n");
      out.write("   rel='stylesheet' type='text/css'>\r\n");
      out.write("<link\r\n");
      out.write("   href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'\r\n");
      out.write("   rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(function(){\r\n");
      out.write("	   $(\"span#mod\").click(function(){\r\n");
      out.write("		  $(\"form\").submit(); \r\n");
      out.write("	   });\r\n");
      out.write("   }); \r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- Page Header -->\r\n");
      out.write("   <!-- Set your background image for this header on the line below. -->\r\n");
      out.write("   <header class=\"intro-header\"\r\n");
      out.write("      style=\"background-image: url('img/about-bg.jpg'); height: 200px\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1\">\r\n");
      out.write("               <div class=\"site-heading\"\r\n");
      out.write("                  style=\"margin-top: 10px; padding-top: 35px; padding-bottom: 35px\">\r\n");
      out.write("                  <h2>SAMPLE</h2>\r\n");
      out.write("                  <span class=\"subheading\">BULLETIN BOARD</span>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </header>\r\n");
      out.write("   <div class=\"board-field\">\r\n");
      out.write("     <form action=\"/Web/modifyProcessAction.do\" method=\"post\">\r\n");
      out.write("      <div class=\"list-group\">\r\n");
      out.write("         <div class=\"list-group-item board-title\">\r\n");
      out.write("            <div class=\"board-title\">\r\n");
      out.write("               <span class=\"board-category\">[TITLE]</span><a href=\"#\">\r\n");
      out.write("                  <input name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  style=\"height: 25px;\">  </a> \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"board-meta\"\r\n");
      out.write("               style=\"font-weight: 400; font-size: 1.2rem; color: #404040\">\r\n");
      out.write("               <p>\r\n");
      out.write("                  <i class=\"glyphicon glyphicon-user\"><input type=\"text\" name=\"author\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.author }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> 님</i>\r\n");
      out.write("                  <input type=\"hidden\" name=\"no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">   \r\n");
      out.write("                  <i class=\"glyphicon glyphicon-comment\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.reply}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</i> \r\n");
      out.write("                  <i class=\"glyphicon glyphicon-ok\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.hit}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</i>  \r\n");
      out.write("                  <i class=\"glyphicon glyphicon-time\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.regdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</i>\r\n");
      out.write("                   <i class=\"glyphicon glyphicon-thumbs-up\"></i> 0\r\n");
      out.write("                  <i class=\"glyphicon glyphicon-thumbs-down\"></i> 0\r\n");
      out.write("               </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"clear\"></div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"list-group-item\">             \r\n");
      out.write("            <span class=\"board-contents\">\r\n");
      out.write("            <textarea name=\"contents\" cols=\"180\" rows=\"10\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("             </span>\r\n");
      out.write("            <p style=\"text-align: center; margin-top: 30px\">\r\n");
      out.write("               <button class=\"btn btn-success\">\r\n");
      out.write("                  <i class=\"glyphicon glyphicon-thumbs-up\"></i>공감\r\n");
      out.write("               </button>\r\n");
      out.write("               <button class=\"btn btn-warning\">\r\n");
      out.write("                  <i class=\"glyphicon glyphicon-thumbs-down\"></i>비공감\r\n");
      out.write("               </button>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"bottom\" style=\"margin: 10px;margin-top: 20px; text-align: right\">\r\n");
      out.write("            <a href=\"/Web/boardMVC/boardList.do\" class=\"btn btn-default btn-xs pull-left\">목록으로</a> \r\n");
      out.write("            <a href=\"#\" class=\"btn btn-default btn-xs\" lang=\"mod\"><span id=\"mod\">수정</span></a> \r\n");
      out.write("            <a href=\"/Web/boardMVC/boardInfo.do?no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${info.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&job=info\" class=\"btn btn-default btn-xs\" lang=\"del\">취소</a>\r\n");
      out.write("            \r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"clear\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- Footer -->\r\n");
      out.write("   <footer>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1\">\r\n");
      out.write("               <ul class=\"list-inline text-center\">\r\n");
      out.write("                  <li><a href=\"#\"> <span class=\"fa-stack fa-lg\"> <i\r\n");
      out.write("                           class=\"fa fa-circle fa-stack-2x\"></i> <i\r\n");
      out.write("                           class=\"fa fa-envelope-o fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("                     </span>\r\n");
      out.write("                  </a></li>\r\n");
      out.write("                  <li><a href=\"#\"> <span class=\"fa-stack fa-lg\"> <i\r\n");
      out.write("                           class=\"fa fa-circle fa-stack-2x\"></i> <i\r\n");
      out.write("                           class=\"fa fa-home fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("                     </span>\r\n");
      out.write("                  </a></li>\r\n");
      out.write("                  <li><a href=\"#\"> <span class=\"fa-stack fa-lg\"> <i\r\n");
      out.write("                           class=\"fa fa-circle fa-stack-2x\"></i> <i\r\n");
      out.write("                           class=\"fa fa-github fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("                     </span>\r\n");
      out.write("                  </a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("               <p class=\"copyright text-muted\">Copyright &copy;2016 SIST. All\r\n");
      out.write("                  rights reserved | code by milib</p>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("   <!-- jQuery -->\r\n");
      out.write("   <script src=\"js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("   <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <!-- Custom Theme JavaScript -->\r\n");
      out.write("   <script src=\"js/clean-blog.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
