/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-10-13 03:40:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.boardMVC;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/82106/SpringLesson2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springWeb/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1632793742027L));
    _jspx_dependants.put("jar:file:/C:/Users/82106/SpringLesson2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springWeb/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC >\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Start Simple Web</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"css/clean-blog.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("	href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'\r\n");
      out.write("	rel='stylesheet' type='text/css'>\r\n");
      out.write("<link\r\n");
      out.write("	href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'\r\n");
      out.write("	rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("p {\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination {\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-family: Helvetica Neue, Helvetica, Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination>li>a {\r\n");
      out.write("	color: #404040;\r\n");
      out.write("	float: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination>.active>a, .pagination>.active>a:hover, .pagination>.active>a:focus\r\n");
      out.write("	{\r\n");
      out.write("	z-index: 3;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	cursor: default;\r\n");
      out.write("	background-color: #404040;\r\n");
      out.write("	border-color: #404040;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination>li>a:hover, .pagination>li>a:focus {\r\n");
      out.write("	z-index: 3;\r\n");
      out.write("	color: black;\r\n");
      out.write("	cursor: default;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border-color: #404040;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".glyphicon {\r\n");
      out.write("	margin-left: 10px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-category {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	color: #404040;\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("	margin-left: 20px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-field {\r\n");
      out.write("	margin-bottom: 30px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 6px 12px;\r\n");
      out.write("	margin-bottom: 0px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	line-height: 1.4285;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	-ms-touch-action: manipulation;\r\n");
      out.write("	touch-action: manipulation;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	-webkit-user-select: none;\r\n");
      out.write("	-moz-user-select: none;\r\n");
      out.write("	-ms-user-select: none;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("	background-image: none;\r\n");
      out.write("	border: 1px solid transparent;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("	background-color: #3b3b3b;\r\n");
      out.write("	border-color: #282828;\r\n");
      out.write("	background-color: #3b3b3b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover, .btn-primary:focus, .btn-primary:active,\r\n");
      out.write("	.btn-primary.active, .open .dropdown-toggle.btn-primary {\r\n");
      out.write("	background-color: #282828;\r\n");
      out.write("	border-color: #080808;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover, .btn-primary:focus, .btn-primary:active,\r\n");
      out.write("	.btn-primary.active, .open>.dropdown-toggle.btn-primary {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	background-color: gray;\r\n");
      out.write("	border-color: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-sm, .btn-group-sm>.btn {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 13px 13px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	line-height: 1.5;\r\n");
      out.write("	/*     border-radius: 3px; */\r\n");
      out.write("	border-top: 35px;\r\n");
      out.write("	padding: 13px 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field {\r\n");
      out.write("	padding: 0 0 30px 0;\r\n");
      out.write("	font-family: Helvetica Neue, Helvetica, Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field table {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border: 0;\r\n");
      out.write("	border-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field td {\r\n");
      out.write("	padding: 8px 0 8px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .td1 {\r\n");
      out.write("	width: 70px;\r\n");
      out.write("	min-height: 30px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #666;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .td1.vtop {\r\n");
      out.write("	vertical-align: top;\r\n");
      out.write("	padding-top: 10px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .td2 input[type=\"text\"], input[type=\"password\"] {\r\n");
      out.write("	height: 28px;\r\n");
      out.write("	padding: 3px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	-webkit-box-sizing: border-box;\r\n");
      out.write("	-moz-box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .input-title {\r\n");
      out.write("	float: left;\r\n");
      out.write("	color: #666;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	line-height: 30px;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	width: 70px;\r\n");
      out.write("	margin: 4px 0 4px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .input-forms {\r\n");
      out.write("	margin: 4px 0 4px 0;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .input-name {\r\n");
      out.write("	height: 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .input-pwd {\r\n");
      out.write("	height: 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .td2 .more {\r\n");
      out.write("	width: 85%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .td2 select {\r\n");
      out.write("	min-width: 155px;\r\n");
      out.write("	max-width: 250px;\r\n");
      out.write("	height: 28px;\r\n");
      out.write("	padding: 2px;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .td2 .guide {\r\n");
      out.write("	font-size: 90%;\r\n");
      out.write("	font-family: dotum;\r\n");
      out.write("	color: #999;\r\n");
      out.write("	padding: 3px 0 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .td2 .guide img {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: -1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .td2 .check-label {\r\n");
      out.write("	color: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .td2 .after {\r\n");
      out.write("	padding: 10px 0 0 0;\r\n");
      out.write("	color: #999;\r\n");
      out.write("	font-family: dotum;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .td2 .after input {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .editbox {\r\n");
      out.write("	padding: 15px 0 15px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .iconbox {\r\n");
      out.write("	border-left: #e0e0e0 solid 1px;\r\n");
      out.write("	border-top: #e0e0e0 solid 1px;\r\n");
      out.write("	border-right: #e0e0e0 solid 1px;\r\n");
      out.write("	background: #f9f9f9;\r\n");
      out.write("	padding: 6px 0 8px 7px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .iconbox a {\r\n");
      out.write("	padding: 0 3px 0 3px;\r\n");
      out.write("	font-family: dotum;\r\n");
      out.write("	color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .iconbox a:hover {\r\n");
      out.write("	color: #7899C7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .iconbox a img {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: -1px;\r\n");
      out.write("	margin-right: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .iconbox .split {\r\n");
      out.write("	padding: 0 2px 0 2px;\r\n");
      out.write("	margin-bottom: -1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .bottombox {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 20px 0 20px 0;\r\n");
      out.write("	margin: 15px 0 0 0;\r\n");
      out.write("	border-top: #efefef solid 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .bottombox .btngray {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width: 60px;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write-field .bottombox .btnblue {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width: 80px;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("	$(\"button#submitPost\").click(function(){\r\n");
      out.write("		$(\"form\").submit();\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<!--info에서 보낸 변수들 여기서 다 받음.  -->\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Page Header -->\r\n");
      out.write("	<!-- Set your background image for this header on the line below. -->\r\n");
      out.write("	<header class=\"intro-header\"\r\n");
      out.write("		style=\"background-image: url('img/about-bg.jpg'); height: 200px\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1\">\r\n");
      out.write("					<div class=\"site-heading\"\r\n");
      out.write("						style=\"margin-top: 10px; padding-top: 35px; padding-bottom: 35px\">\r\n");
      out.write("						<h2>SAMPLE</h2>\r\n");
      out.write("						<span class=\"subheading\">BULLETIN BOARD</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<form action=\"boardInsert.do\" method=\"post\" name=\"insertFrm\" enctype=\"multipart/form-data\">\r\n");
      out.write("	<div id=\"write-field\">\r\n");
      out.write("		<div class=\"col-md-3\"></div>\r\n");
      out.write("		<div class=\"col-md-6\">\r\n");
      out.write("			<table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"td2\" colspan=\"2\">\r\n");
      out.write("						<div class=\"row row-xs-bskr\">\r\n");
      out.write("							<div class=\"col-md-6 col-sm-6 col-xs-bskr\">\r\n");
      out.write("								<div class=\"input-title\">작성자명</div>\r\n");
      out.write("								<div class=\"input-forms\">\r\n");
      out.write("									<input size=\"20\" type=\"text\" name=\"author\" value=\"\"\r\n");
      out.write("										class=\"form-control input-sm input-name bskr-font user\" />\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6 col-sm-6 col-xs-bskr\">\r\n");
      out.write("								<div class=\"input-title\">비밀번호</div>\r\n");
      out.write("								<div class=\"input-forms\">\r\n");
      out.write("									<input size=\"20\" type=\"password\" name=\"password\" value=\"\"\r\n");
      out.write("										class=\"form-control input-sm input-pwd bskr-font user\" />\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"td1\">제목</td>\r\n");
      out.write("					<td class=\"td2\" valign=\"middle\"><input type=\"text\"\r\n");
      out.write("						name=\"title\" value=\"\"\r\n");
      out.write("						class=\"form-control input-sm bskr-font subject\" />\r\n");
      out.write("						<input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">	\r\n");
      out.write("                 <!--  목록에서 쓰기로 넘어오는 경우는 job값이 없으므로 해당 값 처리 -->\r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                  </td>\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"td1\"></td>\r\n");
      out.write("						<td calss=\"td2\"><textarea name=\"contents\" class=\"form-control col-sm-5\"\r\n");
      out.write("								rows=\"20\"></textarea></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("					<td class=\"td1\"></td>\r\n");
      out.write("						<td class=\"td2\"><input type=\"file\" id=\"InputFile\" name=\"file\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"bottombox\">\r\n");
      out.write("				<input type=\"button\" value=\"취소\" class=\"btn btn-default btn-sm\"\r\n");
      out.write("					onclick=\"return cancelCheck();\" />&nbsp;\r\n");
      out.write("				<button id=\"submitPost\" type=\"button\" class=\"btn btn-primary btn-sm\">\r\n");
      out.write("					<i class=\"glyphicon glyphicon-ok\">확인</i>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1\">\r\n");
      out.write("					<ul class=\"list-inline text-center\">\r\n");
      out.write("						<li><a href=\"#\"> <span class=\"fa-stack fa-lg\"> <i\r\n");
      out.write("									class=\"fa fa-circle fa-stack-2x\"></i> <i\r\n");
      out.write("									class=\"fa fa-envelope-o fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"#\"> <span class=\"fa-stack fa-lg\"> <i\r\n");
      out.write("									class=\"fa fa-circle fa-stack-2x\"></i> <i\r\n");
      out.write("									class=\"fa fa-home fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li><a href=\"#\"> <span class=\"fa-stack fa-lg\"> <i\r\n");
      out.write("									class=\"fa fa-circle fa-stack-2x\"></i> <i\r\n");
      out.write("									class=\"fa fa-github fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("							</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<p class=\"copyright text-muted\">Copyright &copy;2016 SIST. All\r\n");
      out.write("						rights reserved | code by milib</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- jQuery -->\r\n");
      out.write("	<script src=\"js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Custom Theme JavaScript -->\r\n");
      out.write("	<script src=\"js/clean-blog.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /boardMVC/write.jsp(302,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("job");
      // /boardMVC/write.jsp(302,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.job}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /boardMVC/write.jsp(303,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("ref");
      // /boardMVC/write.jsp(303,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.ref}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /boardMVC/write.jsp(304,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("step");
      // /boardMVC/write.jsp(304,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.step}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /boardMVC/write.jsp(305,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("lev");
      // /boardMVC/write.jsp(305,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.lev}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f4_reused = false;
    try {
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent(null);
      // /boardMVC/write.jsp(306,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setVar("pnum");
      // /boardMVC/write.jsp(306,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pnum}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      _jspx_th_c_005fset_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /boardMVC/write.jsp(309,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${job}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  \r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /boardMVC/write.jsp(369,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${job eq '' or job==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                      <input type=\"hidden\" value=\"new\" name=\"job\">\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <input type=\"hidden\" value=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${job}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" name=\"job\">\r\n");
          out.write("                    <input type=\"hidden\" value=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ref }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" name=\"ref\">\r\n");
          out.write("                    <input type=\"hidden\" value=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${step }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" name=\"step\">\r\n");
          out.write("                    <input type=\"hidden\" value=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lev }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" name=\"lev\">\r\n");
          out.write("                    <input type=\"hidden\" value=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pnum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" name=\"pnum\">\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
