/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-10-26 05:26:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bootstrap;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class movieReservation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/82106/SpringLesson2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1632793742027L));
    _jspx_dependants.put("jar:file:/C:/Users/82106/SpringLesson2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/webProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("        <!--Google Fonts link-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Crimson+Text:400,400i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slick.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/slick-theme.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animate.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/fonticons.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/font-awesome.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/bootstrap.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/magnific-popup.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/bootsnav.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--For Plugins external css-->\r\n");
      out.write("        <!--<link rel=\"stylesheet\" href=\"assets/css/plugins.css\" />-->\r\n");
      out.write("\r\n");
      out.write("        <!--Theme custom css -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("        <!--<link rel=\"stylesheet\" href=\"assets/css/colors/maron.css\">-->\r\n");
      out.write("\r\n");
      out.write("        <!--Theme Responsive css-->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/responsive.css\" />\r\n");
      out.write("\r\n");
      out.write("        <script src=\"assets/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	var dt=new Date(); //현재날짜&시간\r\n");
      out.write("	var m=dt.getMonth()+1; //월은 0부터 시작해서 1 더해줘야함\r\n");
      out.write("	if(m<10){\r\n");
      out.write("		var month=\"0\"+m;\r\n");
      out.write("	}else{\r\n");
      out.write("		var month=m;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var d=dt.getDate()-1; //하루전꺼 검색\r\n");
      out.write("	if(d<10){\r\n");
      out.write("		var day=\"0\"+d;\r\n");
      out.write("	}else{\r\n");
      out.write("		var day=d;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	var year=dt.getFullYear();\r\n");
      out.write("	var result=year+\"\"+month+\"\"+day;\r\n");
      out.write("	var result2=year+\".\"+month+\".\"+day;\r\n");
      out.write("	$(function(){\r\n");
      out.write("		//상단에 어제 일자 출력\r\n");
      out.write("		$(\"h2#today\").html(result2+\" 일별 박스오피스 순위\");\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"https://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=12ff9134153dd158e068074390244746&targetDt=\"+result,\r\n");
      out.write("			dataType:\"json\",\r\n");
      out.write("			success:function(v){\r\n");
      out.write("				var movieData=v[\"boxOfficeResult\"][\"dailyBoxOfficeList\"];\r\n");
      out.write("				//반복문 돌려서 데이터 10개 모두 출력함\r\n");
      out.write("				var temp=\"\";\r\n");
      out.write("				$.each(movieData,function(index,value){\r\n");
      out.write("					//console.log(value.movieNm);\r\n");
      out.write("					var moviecode=value.movieCd;\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url:\"/webProject/movieImg.do\",\r\n");
      out.write("						dataType:\"text\",\r\n");
      out.write("						data: {moviecode: moviecode},\r\n");
      out.write("						success:function(v){\r\n");
      out.write("							$(\"img#img\"+index).attr(\"src\",v);\r\n");
      out.write("						},\r\n");
      out.write("						error:function(v){\r\n");
      out.write("							console.log(\"error\");\r\n");
      out.write("						}\r\n");
      out.write("						\r\n");
      out.write("					});\r\n");
      out.write("						temp+=\"<div class=\\\"col-md-4\\\">\";\r\n");
      out.write("						temp+=\"<div class=\\\"blog_item m-top-30\\\">\";\r\n");
      out.write("						temp+=\"<div class=\\\"blog_item_img\\\">\";\r\n");
      out.write("						temp+=\"<img id=img\"+index+\" src=\\\"assets/images/blog/2.jpg\\\" alt=\\\"\\\" />\";\r\n");
      out.write("						temp+=\"</div>\";\r\n");
      out.write("						temp+=\"<ol class=\\\"breadcrumb\\\">\";\r\n");
      out.write("						temp+=\"<li><a href=\\\"#\\\" class=\\\"text-black\\\">\"+value.rank+\"위</a></li>\";\r\n");
      out.write("						temp+=\"<li><a href=\\\"#\\\" class=\\\"text-black\\\">개봉일:\"+value.openDt+\"</a></li>\";\r\n");
      out.write("						temp+=\"</ol>\";\r\n");
      out.write("						temp+=\"<h5>\"+value.movieNm+\"</h5>\";\r\n");
      out.write("						temp+=\"<p class=\\\"m-top-20\\\">관객수:\"+value.audiCnt+\"<br>누적 관객수:\"+value.audiAcc+\"</p>\";\r\n");
      out.write("						temp+=\"</div>\";\r\n");
      out.write("						temp+=\"</div>\";\r\n");
      out.write("				$(\"div#dailyMovie\"+index).html(temp);\r\n");
      out.write("				temp=\"\";\r\n");
      out.write("				}); //반복문 종료\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			},\r\n");
      out.write("			error:function(){\r\n");
      out.write("				alert(\"error!\");\r\n");
      out.write("			}	\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".navbar-collapse\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Preloader -->\r\n");
      out.write("\r\n");
      out.write("        <div id=\"loading\">\r\n");
      out.write("            <div id=\"loading-center\">\r\n");
      out.write("                <div id=\"loading-center-absolute\">\r\n");
      out.write("                    <div class=\"object\"></div>\r\n");
      out.write("                    <div class=\"object\"></div>\r\n");
      out.write("                    <div class=\"object\"></div>\r\n");
      out.write("                    <div class=\"object\"></div>\r\n");
      out.write("                    <div class=\"object\"></div>\r\n");
      out.write("                    <div class=\"object\"></div>\r\n");
      out.write("                    <div class=\"object\"></div>\r\n");
      out.write("                    <div class=\"object\"></div>\r\n");
      out.write("                    <div class=\"object\"></div>\r\n");
      out.write("                    <div class=\"object\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!--End off Preloader -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"culmn\">\r\n");
      out.write("            <!--Home page style-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <nav class=\"navbar navbar-default navbar-fixed white no-background bootsnav text-uppercase\">\r\n");
      out.write("                <!-- Start Top Search -->\r\n");
      out.write("                <div class=\"top-search\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-addon\"><i class=\"fa fa-search\"></i></span>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("                            <span class=\"input-group-addon close-search\"><i class=\"fa fa-times\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End Top Search -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container\">    \r\n");
      out.write("                    <!-- Start Atribute Navigation -->\r\n");
      out.write("                    <div class=\"attr-nav\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li class=\"search\"><a href=\"#\"><i class=\"fa fa-search\"></i></a></li>\r\n");
      out.write("                            <li class=\"dropdown\">\r\n");
      out.write("                                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" >\r\n");
      out.write("                                    <i class=\"fa fa-shopping-bag\"></i>\r\n");
      out.write("                                    <span class=\"badge\">3</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu cart-list\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\" class=\"photo\"><img src=\"assets/images/thumb01.jpg\" class=\"cart-thumb\" alt=\"\" /></a>\r\n");
      out.write("                                        <h6><a href=\"#\">Delica omtantur </a></h6>\r\n");
      out.write("                                        <p class=\"m-top-10\">2x - <span class=\"price\">$99.99</span></p>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\" class=\"photo\"><img src=\"assets/images/thumb01.jpg\" class=\"cart-thumb\" alt=\"\" /></a>\r\n");
      out.write("                                        <h6><a href=\"#\">Delica omtantur </a></h6>\r\n");
      out.write("                                        <p class=\"m-top-10\">2x - <span class=\"price\">$99.99</span></p>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <a href=\"#\" class=\"photo\"><img src=\"assets/images/thumb01.jpg\" class=\"cart-thumb\" alt=\"\" /></a>\r\n");
      out.write("                                        <h6><a href=\"#\">Delica omtantur </a></h6>\r\n");
      out.write("                                        <p class=\"m-top-10\">2x - <span class=\"price\">$99.99</span></p>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <!---- More List ---->\r\n");
      out.write("                                    <li class=\"total\">\r\n");
      out.write("                                        <span class=\"pull-right\"><strong>Total</strong>: $0.00</span>\r\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-cart\">Cart</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>        \r\n");
      out.write("                    <!-- End Atribute Navigation -->\r\n");
      out.write("\r\n");
      out.write("                    <!-- Start Header Navigation -->\r\n");
      out.write("                    <div class=\"navbar-header\">\r\n");
      out.write("                        <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-menu\">\r\n");
      out.write("                            <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("\r\n");
      out.write("                            <img src=\"assets/images/logo.png\" class=\"logo logo-display\" alt=\"\">\r\n");
      out.write("                            <img src=\"assets/images/logo-black.png\" class=\"logo logo-scrolled\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End Header Navigation -->\r\n");
      out.write("\r\n");
      out.write("                    <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbar-menu\">\r\n");
      out.write("                        <ul class=\"nav navbar-nav navbar-right\" data-in=\"fadeInDown\" data-out=\"fadeOutUp\">\r\n");
      out.write("                            <li><a href=\"index.html\">home</a></li> \r\n");
      out.write("							<li><a href=\"aboutus.html\">about</a></li> 							                   \r\n");
      out.write("                            <li><a href=\"model.html\">our models</a></li> 							\r\n");
      out.write("                            <li><a href=\"blog.html\">blog</a></li>                                    \r\n");
      out.write("                            <li><a href=\"contactus.html\">contact</a></li>   \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div><!-- /.navbar-collapse -->\r\n");
      out.write("                </div>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!--Home Sections-->\r\n");
      out.write("\r\n");
      out.write("            <section id=\"hello\" class=\"model-banner bg-mega\">\r\n");
      out.write("                <div class=\"overlay\"></div>\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"main_home text-center\">\r\n");
      out.write("                            <div class=\"model_text\">\r\n");
      out.write("                                <h1 class=\"text-white text-uppercase\">OUR MODELS</h1>\r\n");
      out.write("                                <ol class=\"breadcrumb\">\r\n");
      out.write("                                    <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                                    <li class=\"active\"><a href=\"#\">OUR MODELS</a></li>\r\n");
      out.write("                                </ol>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div><!--End off row-->\r\n");
      out.write("                </div><!--End off container -->\r\n");
      out.write("            </section> <!--End off Home Sections-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!--Portfolio Section-->\r\n");
      out.write("            <section id=\"gallery\" class=\"gallery margin-top-120 bg-white\">\r\n");
      out.write("                <!-- Portfolio container-->\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"main-gallery main-model roomy-80\">\r\n");
      out.write("            		    <h2 id=\"today\"></h2>\r\n");
      out.write("<!-- 반복할 데이터 -->\r\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- 여기서 데이터 출력  -->\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!-- Portfolio container end -->\r\n");
      out.write("            </section><!-- End off portfolio section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!--Company section-->\r\n");
      out.write("\r\n");
      out.write("            <section id=\"company\" class=\"company bg-light\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"main_company roomy-100 text-center\">\r\n");
      out.write("                            <h3 class=\"text-uppercase\">pouseidon.</h3>\r\n");
      out.write("                            <p>7th floor - Palace Building - 221b Walk of Fame - London- United Kingdom</p>\r\n");
      out.write("                            <p>(+84). 123. 456. 789  -  info@poiseidon.lnk</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- scroll up-->\r\n");
      out.write("            <div class=\"scrollup\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("            </div><!-- End off scroll up -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <footer id=\"footer\" class=\"footer bg-mega\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"main_footer p-top-40 p-bottom-30\">\r\n");
      out.write("                            <div class=\"col-md-6 text-left sm-text-center\">\r\n");
      out.write("                                <p class=\"wow fadeInRight\" data-wow-duration=\"1s\">\r\n");
      out.write("                                    Made with \r\n");
      out.write("                                    <i class=\"fa fa-heart\"></i>\r\n");
      out.write("                                    by \r\n");
      out.write("                                    <a target=\"_blank\" href=\"http://bootstrapthemes.co\">Bootstrap Themes</a> \r\n");
      out.write("                                    2016. All Rights Reserved\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 text-right sm-text-center sm-m-top-20\">\r\n");
      out.write("                                <ul class=\"list-inline\">\r\n");
      out.write("                                    <li><a href=\"\">Facebook</a></li>\r\n");
      out.write("                                    <li><a href=\"\">Twitter</a></li>\r\n");
      out.write("                                    <li><a href=\"\">Instagram</a></li>\r\n");
      out.write("                                    <li><a href=\"\">Pinterest</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- JS includes -->\r\n");
      out.write("\r\n");
      out.write("        <script src=\"assets/js/vendor/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("        <script src=\"assets/js/vendor/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"assets/js/isotope.min.js\"></script>\r\n");
      out.write("        <script src=\"assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("        <script src=\"assets/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("        <script src=\"assets/js/slick.min.js\"></script>\r\n");
      out.write("        <script src=\"assets/js/jquery.collapse.js\"></script>\r\n");
      out.write("        <script src=\"assets/js/bootsnav.js\"></script>\r\n");
      out.write("        <script src=\"kobisApi.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- paradise slider js -->\r\n");
      out.write("\r\n");
      out.write("        <!--\r\n");
      out.write("                <script src=\"http://maps.google.com/maps/api/js?key=AIzaSyD_tAQD36pKp9v4at5AnpGbvBUsLCOSJx8\"></script>\r\n");
      out.write("                <script src=\"assets/js/gmaps.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("                <script>\r\n");
      out.write("                    function showmap() {\r\n");
      out.write("                        var mapOptions = {\r\n");
      out.write("                            zoom: 8,\r\n");
      out.write("                            scrollwheel: false,\r\n");
      out.write("                            center: new google.maps.LatLng(-34.397, 150.644),\r\n");
      out.write("                            mapTypeId: google.maps.MapTypeId.ROADMAP\r\n");
      out.write("                        };\r\n");
      out.write("                        var map = new google.maps.Map(document.getElementById('map_canvas'), mapOptions);\r\n");
      out.write("                        $('.mapheight').css('height', '350');\r\n");
      out.write("                        $('.maps_text h3').hide();\r\n");
      out.write("                    }\r\n");
      out.write("        \r\n");
      out.write("                </script>-->\r\n");
      out.write("\r\n");
      out.write("        <script src=\"assets/js/plugins.js\"></script>\r\n");
      out.write("        <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /bootstrap/movieReservation.jsp(256,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /bootstrap/movieReservation.jsp(256,7) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(0);
      // /bootstrap/movieReservation.jsp(256,7) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(9);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<div id=\"dailyMovie");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                            </div>\r\n");
            out.write("                           ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
